# Databricks notebook source
dbutils.widgets.removeAll()

# COMMAND ----------

# MAGIC %sql
# MAGIC create widget text storageLocation default "abfss://lhclproject@adlsmartdata2447.dfs.core.windows.net/";

# COMMAND ----------

# MAGIC %md
# MAGIC ### Creacion de catalog

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE EXTERNAL LOCATION IF NOT EXISTS `exlt-lhclproject`
# MAGIC URL '${storageLocation}'
# MAGIC WITH (STORAGE CREDENTIAL `credential`)
# MAGIC COMMENT 'Ubicación externa para el catalogo del proyecto';

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE CATALOG IF NOT EXISTS final_project_flights
# MAGIC MANAGED LOCATION '${storageLocation}';

# COMMAND ----------

# MAGIC %md
# MAGIC ### Creacion de Schemas

# COMMAND ----------

# MAGIC %sql
# MAGIC USE CATALOG final_project_flights;
# MAGIC
# MAGIC CREATE SCHEMA IF NOT EXISTS raw;
# MAGIC CREATE SCHEMA IF NOT EXISTS bronze;
# MAGIC CREATE SCHEMA IF NOT EXISTS silver;
# MAGIC CREATE SCHEMA IF NOT EXISTS golden;

# COMMAND ----------

# MAGIC %md
# MAGIC ### Creacion tablas Bronze

# COMMAND ----------

# MAGIC %sql
# MAGIC USE CATALOG final_project_flights;
# MAGIC USE SCHEMA bronze;
# MAGIC
# MAGIC CREATE OR REPLACE TABLE airlines (
# MAGIC   IATA_CODE STRING,
# MAGIC   AIRLINE STRING
# MAGIC )
# MAGIC USING DELTA
# MAGIC LOCATION '${storageLocation}/bronze/airlines';
# MAGIC
# MAGIC CREATE OR REPLACE TABLE airports (
# MAGIC   IATA_CODE STRING,
# MAGIC   AIRPORT STRING,
# MAGIC   CITY STRING,
# MAGIC   STATE STRING,
# MAGIC   COUNTRY STRING,
# MAGIC   LATITUDE STRING,
# MAGIC   LONGITUDE STRING
# MAGIC )
# MAGIC USING DELTA
# MAGIC LOCATION '${storageLocation}/bronze/airports';
# MAGIC
# MAGIC CREATE OR REPLACE TABLE flights (
# MAGIC     YEAR INT,
# MAGIC     MONTH INT,
# MAGIC     DAY INT,
# MAGIC     DAY_OF_WEEK INT,
# MAGIC     AIRLINE STRING,
# MAGIC     FLIGHT_NUMBER INT,
# MAGIC     TAIL_NUMBER STRING,
# MAGIC     ORIGIN_AIRPORT STRING,
# MAGIC     DESTINATION_AIRPORT STRING,
# MAGIC     SCHEDULED_DEPARTURE INT,
# MAGIC     DEPARTURE_TIME INT,
# MAGIC     DEPARTURE_DELAY INT,
# MAGIC     TAXI_OUT INT,
# MAGIC     WHEELS_OFF INT,
# MAGIC     SCHEDULED_TIME INT,
# MAGIC     ELAPSED_TIME INT,
# MAGIC     AIR_TIME INT,
# MAGIC     DISTANCE INT,
# MAGIC     WHEELS_ON INT,
# MAGIC     TAXI_IN INT,
# MAGIC     SCHEDULED_ARRIVAL INT,
# MAGIC     ARRIVAL_TIME INT,
# MAGIC     ARRIVAL_DELAY INT,
# MAGIC     DIVERTED INT,
# MAGIC     CANCELLED INT,
# MAGIC     CANCELLATION_REASON STRING,
# MAGIC     AIR_SYSTEM_DELAY INT,
# MAGIC     SECURITY_DELAY INT,
# MAGIC     AIRLINE_DELAY INT,
# MAGIC     LATE_AIRCRAFT_DELAY INT,
# MAGIC     WEATHER_DELAY INT
# MAGIC )
# MAGIC USING DELTA
# MAGIC LOCATION '${storageLocation}/bronze/flights';

# COMMAND ----------

# MAGIC %md
# MAGIC ### Creacion tablas Silver

# COMMAND ----------

# MAGIC %sql
# MAGIC USE CATALOG final_project_flights;
# MAGIC USE SCHEMA silver;
# MAGIC
# MAGIC CREATE OR REPLACE TABLE airports_silver (
# MAGIC   IATA_CODE STRING,
# MAGIC   AIRPORT STRING,
# MAGIC   CITY STRING,
# MAGIC   STATE STRING,
# MAGIC   COUNTRY STRING,
# MAGIC   LATITUDE DOUBLE,
# MAGIC   LONGITUDE DOUBLE
# MAGIC )
# MAGIC USING DELTA
# MAGIC LOCATION '${storageLocation}/silver/airports';
# MAGIC
# MAGIC CREATE OR REPLACE TABLE flights_silver (
# MAGIC   DAY_OF_WEEK INT,
# MAGIC   AIRLINE STRING,
# MAGIC   FLIGHT_NUMBER INT,
# MAGIC   TAIL_NUMBER STRING,
# MAGIC   ORIGIN_AIRPORT STRING,
# MAGIC   DESTINATION_AIRPORT STRING,
# MAGIC   DEPARTURE_DELAY INT,
# MAGIC   TAXI_OUT INT,
# MAGIC   SCHEDULED_TIME INT,
# MAGIC   ELAPSED_TIME INT,
# MAGIC   AIR_TIME INT,
# MAGIC   DISTANCE INT,
# MAGIC   TAXI_IN INT,
# MAGIC   ARRIVAL_DELAY INT,
# MAGIC   DIVERTED INT,
# MAGIC   CANCELLED INT,
# MAGIC   CANCELLATION_REASON STRING,
# MAGIC   AIR_SYSTEM_DELAY INT,
# MAGIC   SECURITY_DELAY INT,
# MAGIC   AIRLINE_DELAY INT,
# MAGIC   LATE_AIRCRAFT_DELAY INT,
# MAGIC   WEATHER_DELAY INT,
# MAGIC   SCHEDULED_DEPARTURE_TS TIMESTAMP,
# MAGIC   SCHEDULED_ARRIVAL_TS TIMESTAMP,
# MAGIC   DEPARTURE_TIME_TS TIMESTAMP,
# MAGIC   ARRIVAL_TIME_TS TIMESTAMP,
# MAGIC   AIRLINE_NAME STRING,
# MAGIC   ORIGIN_CITY STRING,
# MAGIC   ORIGIN_STATE STRING,
# MAGIC   ORIGIN_LAT DOUBLE,
# MAGIC   ORIGIN_LON DOUBLE,
# MAGIC   DESTINATION_CITY STRING,
# MAGIC   DESTINATION_STATE STRING,
# MAGIC   DESTINATION_LAT DOUBLE,
# MAGIC   DESTINATION_LON DOUBLE
# MAGIC )
# MAGIC USING DELTA
# MAGIC LOCATION '${storageLocation}/silver/flights';

# COMMAND ----------

# MAGIC %md
# MAGIC ### Creacion tablas Golden

# COMMAND ----------

# MAGIC %sql
# MAGIC USE CATALOG final_project_flights;
# MAGIC USE SCHEMA golden;
# MAGIC
# MAGIC CREATE OR REPLACE TABLE TM_TIEMPO (
# MAGIC   DATE_KEY INT,
# MAGIC   FULL_DATE DATE,
# MAGIC   DAY_OF_WEEK INT,
# MAGIC   DAY_NAME STRING,
# MAGIC   DAY_OF_MONTH INT,
# MAGIC   WEEK_OF_YEAR INT,
# MAGIC   MONTH INT,
# MAGIC   QUARTER INT,
# MAGIC   YEAR INT
# MAGIC )
# MAGIC USING DELTA
# MAGIC LOCATION '${storageLocation}/golden/tm_tiempo';
# MAGIC
# MAGIC CREATE OR REPLACE TABLE TM_AIRPORTS (
# MAGIC   AIRPORT_KEY STRING,
# MAGIC   AIRPORT STRING,
# MAGIC   CITY STRING,
# MAGIC   STATE STRING,
# MAGIC   GEO_LAT DOUBLE,
# MAGIC   GEO_LONG DOUBLE
# MAGIC )
# MAGIC USING DELTA
# MAGIC LOCATION '${storageLocation}/golden/tm_airports';
# MAGIC
# MAGIC CREATE OR REPLACE TABLE RPT_RESUMEN_VUELOS_DIARIO (
# MAGIC   DATE_KEY INT,
# MAGIC   SCHEDULED_DATE DATE,
# MAGIC   AIRLINE STRING,
# MAGIC   MAYOR_CAUSA_RETRASO STRING,
# MAGIC   TOTAL_FLIGHTS BIGINT,
# MAGIC   TOTAL_DISTANCE_MILES DOUBLE,
# MAGIC   TOTAL_CANCELLED BIGINT,
# MAGIC   TOTAL_DIVERTED BIGINT,
# MAGIC   AVG_DEPARTURE_DELAY_MIN DOUBLE,
# MAGIC   AVG_ARRIVAL_DELAY_MIN DOUBLE,
# MAGIC   FLIGHTS_ON_TIME_COUNT BIGINT,
# MAGIC   CANCELLATION_RATE DOUBLE,
# MAGIC   ON_TIME_PERFORMANCE_RATE DOUBLE
# MAGIC )
# MAGIC USING DELTA
# MAGIC LOCATION '${storageLocation}/golden/rpt_resumen_vuelos_diario';
# MAGIC
# MAGIC CREATE OR REPLACE TABLE TR_PERFORMANCE_RUTA (
# MAGIC   YEAR_MONTH INT,
# MAGIC   AIRLINE STRING,
# MAGIC   ORIGIN_AIRPORT STRING,
# MAGIC   DESTINATION_AIRPORT STRING,
# MAGIC   TIPO_RUTA STRING,
# MAGIC   TOTAL_FLIGHTS_ROUTE BIGINT,
# MAGIC   AVG_AIR_TIME_MIN DOUBLE,
# MAGIC   AVG_DEPARTURE_DELAY_MIN DOUBLE,
# MAGIC   AVG_ARRIVAL_DELAY_MIN DOUBLE,
# MAGIC   AVG_DISTANCE_MILES DOUBLE
# MAGIC )
# MAGIC USING DELTA
# MAGIC LOCATION '${storageLocation}/golden/tr_performance_ruta';
